### ISSUE TITLE
Issue with Empty Table of Contents for LCP-Protected PDFs in Readium 2.4.0

### ISSUE THREAD

**Issue by nageshwararao1988** [readium/kotlin-toolkit#577] opened 2024-10-07 07:28 UTC
### Describe the bug

When loading LCP-protected PDFs in the Android app, the Table of Contents (ToC) is not displayed. This results in an empty ToC list, making it difficult for users to navigate the document effectively.

### How to reproduce?

1.Load an LCP-protected PDF file in the app.
2.Attempt to access the Table of Contents.
3.Observe that the ToC is empty or does not appear at all.

### Readium version

2.4.0

### Android API version

All

### Additional context

Has anyone encountered a similar issue or have any suggestions on how to resolve this? Any guidance would be greatly appreciated!

**Comment by qnga** [comment] 2024-10-07 08:21
Duplicate of #273.

**Closed by qnga** 2024-10-07 08:21 UTC
Labels: bug, triage

**Comment by nageshwararao1988** [comment] 2024-10-07 17:33
![toc](https://github.com/user-attachments/assets/4082f5be-a0ed-43d2-9043-d1a21ffe720e)
